version: '3.8'

services:
  db:
    image: postgres:13
    container_name: vk_test_db
    environment:
      POSTGRES_USER: vkuser
      POSTGRES_PASSWORD: vkpassword
      POSTGRES_DB: vkdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  app:
    build: .
    container_name: vk_test_app
    environment:
      CONFIG_PATH: /root/config/conf.yaml
    depends_on:
      - db
      - kafka
    volumes:
      - ./config:/root/config
    ports:
      - "8080:8080"  # если ваше приложение использует этот порт

volumes:
  db_data:
