database:
  host: "db"
  user: "testuser"
  password: "testpassword"
  dbname: "testdb"
  port: 5432
  sslmode: "disable"
  timezone: "UTC"
kafka:
  brokers:
    - "kafka:9092"
  topic: "test-topic"
  processed_topic: "processed-topic"
