database:
  host: ${DB_HOST}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  dbname: ${DB_NAME}
  port: ${DB_PORT}
  sslmode: ${DB_SSLMODE}
  timezone: ${DB_TIMEZONE}
kafka:
  brokers:
    - ${KAFKA_BROKERS}
  topic: ${KAFKA_TOPIC}
  processed_topic: ${KAFKA_PROCESSED_TOPIC}
